name: Run NestJS tests
on:
  pull_request:
    paths:
      - 'challenge-5/**'
jobs:
  nestjs-tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./challenge-5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}
      - run: yarn test
        working-directory: ${{ env.working-directory }}
